/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shsmp.paper;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
//        Main classUnderTest = new Main();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
        assertTrue(1+1 == 2, "SomeTEstMETHOD");
    }
}
